<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_resultsTitle</name>
   <tag></tag>
   <elementGuidId>038de07a-bfa2-4db1-9d60-421b862f0686</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h3</value>
   </webElementProperties>
</WebElementEntity>
